AWSTemplateFormatVersion: 2010-09-09
Description: Creating Infrastructure for application
Resources:
  MyVPC: 
    Type: AWS::EC2::VPC
    Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: 'true'
        EnableDnsSupport: 'true'
        InstanceTenancy: 'default'
        Tags: 
            - Key: Name
              Value: CF_VPC
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
        VpcId: 
            Ref: MyVPC
        AvailabilityZone: ap-south-1a
        CidrBlock: 10.0.0.0/24
        Tags: 
            - Key: Name
              Value: Pub_Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
        VpcId: 
            Ref: MyVPC
        AvailabilityZone: ap-south-1b
        CidrBlock: 10.0.1.0/24
        Tags: 
            - Key: Name
              Value: Pvt_Subnet
  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: CF_IGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
        VpcId:
            Ref: MyVPC
        InternetGatewayId:
            Ref: myInternetGateway
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
        Tags: 
            - Key: Name
              Value: Pub_RT
        VpcId: 
            Ref: MyVPC
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
        Tags: 
            - Key: Name
              Value: Pvt_RT
        VpcId: 
            Ref: MyVPC
  PubSubnetRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
        RouteTableId: 
            Ref: PublicRouteTable
        SubnetId: 
            Ref: PublicSubnet
  PvtSubnetRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
        RouteTableId: 
            Ref: PrivateRouteTable
        SubnetId: 
            Ref: PrivateSubnet