AWSTemplateFormatVersion: 2010-09-09
Description: Creating Infrastructure for application
Resources:
  MyVPC: 
    Type: AWS::EC2::VPC
    Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: 'true'
        EnableDnsSupport: 'true'
        InstanceTenancy: 'default'
        Tags: 
            - Key: Name
              Value: CF_VPC

